### ISSUE TITLE
style(): improve looking of the badges using badgerbadgerbadger

### ISSUE THREAD

**Issue by Lordnoname** [Werdenfels-Gymnasium/WG-Hilfe#35]
improve looking of the badges and customibility using badgerbadgerbadger and shields.io

**Comment by Lordnoname** [comment]
@DevVersion what do you think about this?

**Comment by DevVersion** [comment]
Not good. We should use the dynamic badges as already used in TravisCI just space them in the headrow

**Comment by Lordnoname** [comment]
The badges are dynamic...they have just another design ajusted to the github guidelines

**Comment by DevVersion** [comment]
There are no official guidelines. Travis Badge and Gitter Badge looking already good enough. Adding other badges wouldn't make any sense. For example the coverage.

**Comment by Lordnoname** [comment]
I would have added a license and dependency badge

**Comment by DevVersion** [comment]
No need to be honest, we are not providing any API. The only thing I can think about, is the dependency badge. Make a PR and show me.

**Comment by Lordnoname** [comment]
Another advantage is that the badges are not confusing in the Readme.md, but in a separate gemfile.
