### ISSUE TITLE
style(): change primary color

### ISSUE THREAD

**Issue by moritzkoenig** [Werdenfels-Gymnasium/WG-Hilfe#37]
I don't like the new color. Please replace it with #FF0080. It looks fresher than your blue.

**Comment by Lordnoname** [comment]
@moritzkoenig @DevVersion I would just highlight the collapsed menu items from the normal menu items (another indention?) and change the color of the menu back to white.

**Comment by DevVersion** [comment]
@Lordnoname @moritzkoenig Stop abusing the issue tracking feature.
Closed through rejection!

**Comment by Lordnoname** [comment]
My thought was serious. I don't like the new color of the menu which is equal to the background. I think a brighter color would match the theme better.

**Comment by DevVersion** [comment]
IMO it looks good. So I denied that request.
