### ISSUE TITLE
fix(): fix WG-Hilfe page for chrome

### ISSUE THREAD

**Issue by Lordnoname** [Werdenfels-Gymnasium/WG-Hilfe#40]
fix WG-Hilfe page for chrome:
![https://gyazo.com/5dfb80857b8f41be6c238fe51307e36c](https://i.gyazo.com/5dfb80857b8f41be6c238fe51307e36c.png)

**Comment by DevVersion** [comment]
Can't reproduce. Needs investigation and more details. @Lordnoname. As always provide Browser Version / Render Engine etc, when filing an issue.

![](https://i.gyazo.com/3438aa5d605fe7b1bbef3d3eff53f1b9.png)

**Comment by Lordnoname** [comment]
@DevVersion This issue is fixed now.
