### ISSUE TITLE
fix(): remove 404 link from index.html

### ISSUE THREAD

**Issue by Lordnoname** [Werdenfels-Gymnasium/WG-Hilfe#47]
remove 404 link from index.html: https://goo.gl/N6KZhF

**Comment by DevVersion** [comment]
Please provide more information? Which link? and maybe provide a screenshot to allow better Investigation.

**Comment by Lordnoname** [comment]
The goo.gl link leads to a 404 github site:
[![https://gyazo.com/43dff69ff4a47f571c56e48ae7d33071](https://i.gyazo.com/43dff69ff4a47f571c56e48ae7d33071.png)](https://goo.gl/N6KZhF)

**Comment by DevVersion** [comment]
Why has Moritz deleted his account?

**Comment by DevVersion** [comment]
Can you create PR, which refers to the `Werdenfels-Gymnasium` Organization

**Comment by Lordnoname** [comment]
I don't know why...he said he don't need his account anymore. :sob:

**Comment by Lordnoname** [comment]
Should i use a shortener again?

**Comment by DevVersion** [comment]
Yes
