### ISSUE TITLE
update(): update pgp tutorial to match the screenshot buttons

### ISSUE THREAD

**Issue by Lordnoname** [Werdenfels-Gymnasium/WG-Hilfe#48]
Tutorial contradict the screenshot:
![https://gyazo.com/1acf2f36b3ab542ed9c83e6cbf76ce3f](https://i.gyazo.com/1acf2f36b3ab542ed9c83e6cbf76ce3f.png)
Maybe we should complete the steps by adding `und klicke auf Weiter`

**Comment by gilgda** [comment]
Working on it, screenshots will be changed after the holidays

**Comment by gilgda** [comment]
Spotted another big problem: PGP has been replaced by Enigmail as far as I can see; going to change the whole tutorial on Friday

**Comment by Lordnoname** [comment]
This issue is not needed anymore
