### ISSUE TITLE
view: add mobile viewport meta tag

### ISSUE THREAD

**Issue by Lordnoname** [Werdenfels-Gymnasium/WG-Hilfe#53]
Better description will follow.

**Comment by DevVersion** [comment]
@Lordnoname Wan't to fix this one? If not, remove your assignment

**Comment by DevVersion** [comment]
@Lordnoname - ping

**Comment by Lordnoname** [comment]
@DevVersion There is already a viewport meta tag. I think the issue is that the ng-view div has `width: 100%` and `padding: 8px`. That's because the view is scrollable for 8px.
