### ISSUE TITLE
update(): improve `Änderungen beitragen` tutorial

### ISSUE THREAD

**Issue by Lordnoname** [Werdenfels-Gymnasium/WG-Hilfe#60]
Replace `git add .` in commit message with `git commit -a -m "message"`
And replace the commit message link like this:
```
Types:

feat: Add new feature
fix: Fix a bug
docs: Change the documentation only
style: Changes that do not affect the meaning of the code like: code formatting, removing Paul G. from the project or removing unnessecary whitespaces
refactor: A code change that neither fixes a bug nor adds a feature nor is a style change
chore: Changes that don't modify `src` or `test` files
perf: Changes that the performance of this build
test: Add missing tests or fix existing tests
build Changes that affect the build cycle or that manages the dependencies (npm or gulp)
```

**Comment by DevVersion** [comment]
That's how it currently should work. Except that we apply brackets after the type.

**Comment by Lordnoname** [comment]
This should be an explanation for all new contributors. Until now we have this link (http://goo.gl/U2hMgE) to explain the types.

**Comment by DevVersion** [comment]
Good idea, I will create a little `CONTRIBUTING.MD` which will be automatically mapped by GitHub

**Comment by Lordnoname** [comment]
Nice! Should I translate my example into German?

**Comment by DevVersion** [comment]
No no need thank you, I think contributing is still desired to be in english.

**Comment by Lordnoname** [comment]
Yeah that's right!
