### ISSUE TITLE
docs(): tutorial for persistent user configs in school

### ISSUE THREAD

**Issue by DevVersion** [Werdenfels-Gymnasium/WG-Hilfe#61]
We need a tutorial to map the local settings in `Home_auf_Server`

**Comment by DevVersion** [comment]
@Lordnoname Like to submit a PR?

**Comment by Lordnoname** [comment]
You mean how-to locate the `Einstellungen` folder?

**Comment by DevVersion** [comment]
No, not really. 
We map our core settings in `Home_auf_Server/Einstellungen` by default (like `firefox` etc).
They are mapped for example from `~/.mozilla/` into `~/Home_auf_Server/Einstellungen/.mozilla`.

But the defaults are limited, so for example if I want to have my `.gitconfig` saved permanently, then I need to copy the `.gitconfig` into `Home_auf_Server/Einstellungen` and it will be automatically mapped after a restart. This should be explained in a tutorial and maybe an example.

**Comment by Lordnoname** [comment]
Ahh ok. Yes I'll do that Friday.

**Comment by DevVersion** [comment]
Very nice :+1: Thanks.
