### ISSUE TITLE
feat(): programming tutorial

### ISSUE THREAD

**Issue by gilgda** [Werdenfels-Gymnasium/WG-Hilfe#67]
Maybe it would be a good idea to create some tutorials about basic programming
- [ ] Java in BlueJ

**Comment by DevVersion** [comment]
I like the idea, should be definitely implemented - :+1:

**Comment by gilgda** [comment]
The tutorial is going to be a basic BlueJ tutorial or something in that direction; will be added by Andi (after he registered himself on Github :sweat_smile: )

**Comment by DevVersion** [comment]
@gilgda Awesome, looking forward seeing it.

**Comment by Lordnoname** [comment]
@Schweinerei33 Ping. If you don't want to do this issue, simply remove your assignment.

**Comment by Lordnoname** [comment]
@Schweinerei33 Sorry for unassigning you, but you haven't answered for 21 days. @DevVersion I think that @gilgda should try to create a Pull Request for this issue. What's your opinion?

**Comment by DevVersion** [comment]
It's fine :+1:
