### ISSUE TITLE
chore: bower incompatible dependencies

### ISSUE THREAD

**Issue by DevVersion** [Werdenfels-Gymnasium/WG-Hilfe#81]
@Lordnoname Can you fix this error, by updating the bower dependencies to be compatible?

![image](https://cloud.githubusercontent.com/assets/4987015/14405047/c2659946-fe85-11e5-8d51-98f7020ec817.png)

**Comment by DevVersion** [comment]
Ping. @Lordnoname

**Comment by Lordnoname** [comment]
Ups, disregards. Yes Ill fix that. :+1:
