### ISSUE TITLE
fix:    wordwrapping

### ISSUE THREAD

**Issue by gilgda** [Werdenfels-Gymnasium/WG-Hilfe#84]
Some words in the Thunderbird and MySQL tutorial are wrapped/separated so that one connected word shows up in two lines :confused: ; any ideas how to fix it? @DevVersion @Lordnoname

**Comment by Lordnoname** [comment]
@gilgda Try to use the `word-wrap` property in css.

**Comment by Lordnoname** [comment]
Fix by pr #85
